import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router";
import AccidentBooleanField from "../components/ui/AccidentBooleanField";
import Footer from "../components/ui/Footer";
import JourneyHeader from "../components/ui/JourneyHeader";
import TripHeaderSummary from "../components/ui/TripHeaderSummary";
import TripIncidentEvidencePicker from "../components/ui/TripIncidentEvidencePicker";
import { accidentService } from "../services/accident.service";
import type { AccidentDetail } from "../services/accident.service";
import { storageService } from "../services/storage.service";

export default function AccidentFormPage() {
    const id = Number(useParams().accidentId); const navigate = useNavigate(); const [accident, setAccident] = useState<AccidentDetail | null>(null); const [time, setTime] = useState(""); const [location, setLocation] = useState(""); const [description, setDescription] = useState(""); const [driverInjured, setDriverInjured] = useState<boolean | null>(null); const [vehicleDamaged, setVehicleDamaged] = useState<boolean | null>(null); const [thirdParties, setThirdParties] = useState<boolean | null>(null); const [files, setFiles] = useState<File[]>([]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
    useEffect(() => { void accidentService.findById(id).then((data) => { const reportedAt = new Date(data.reportedAt); setAccident(data); setTime(`${String(reportedAt.getHours()).padStart(2, "0")}:${String(reportedAt.getMinutes()).padStart(2, "0")}`); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "No fue posible consultar el accidente")); }, [id]);
    const canSave = Boolean(accident && time && location.trim() && description.trim() && driverInjured !== null && vehicleDamaged !== null && thirdParties !== null);
    const save = async () => { if (!canSave || saving || driverInjured === null || vehicleDamaged === null || thirdParties === null) return; setSaving(true); setError(null); try { const evidences = await Promise.all(files.map((file) => storageService.uploadImage(file, "accidentes", id))); await accidentService.complete(id, { accidentTime: time, location, description, driverInjured, vehicleDamaged, thirdPartiesInvolved: thirdParties, evidences }); navigate("/notifications"); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible enviar el formulario"); } finally { setSaving(false); } };
    return <div className="mx-auto min-h-dvh w-full max-w-md bg-white"><JourneyHeader title="Formulario de accidente" onBack={() => navigate("/notifications")} /><main className="space-y-3 px-4 pb-28">{error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-600">{error}</p>}{accident && <><div><span className="rounded-full bg-red-100 px-2 py-1 text-[10px] font-semibold text-red-600">Pendiente por completar</span><p className="mt-2 text-xs text-gray-500">Completa la información del accidente reportado.</p></div><TripHeaderSummary type={accident.vehicle.type} plate={accident.vehicle.plate} driverName={accident.driverName} /><section className="space-y-4 rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><div className="grid grid-cols-2 gap-2"><label className="text-xs font-semibold">Fecha<input readOnly value={new Date(accident.reportedAt).toLocaleDateString("es-CO")} className="mt-2 w-full rounded-lg border border-gray-200 bg-gray-50 p-2 text-xs" /></label><label className="text-xs font-semibold">Hora<input type="time" value={time} onChange={(event) => setTime(event.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 p-2 text-xs" /></label></div><label className="block text-xs font-semibold">Ubicación o referencia geográfica <span className="text-amber-500">*</span><input maxLength={200} value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Autopista Norte, km 5" className="mt-2 w-full rounded-lg border border-gray-200 p-3 text-sm outline-none focus:border-amber-400" /></label><label className="block text-xs font-semibold">Descripción del accidente <span className="text-amber-500">*</span><textarea maxLength={500} value={description} onChange={(event) => setDescription(event.target.value)} className="mt-2 h-28 w-full resize-none rounded-lg border border-gray-200 p-3 text-sm outline-none focus:border-amber-400" /><span className="block text-right text-[9px] text-gray-400">{description.length}/500</span></label><AccidentBooleanField label="¿Sufriste daños?" value={driverInjured} onChange={setDriverInjured} /><AccidentBooleanField label="¿El vehículo sufrió daños?" value={vehicleDamaged} onChange={setVehicleDamaged} /><AccidentBooleanField label="¿Hay terceros involucrados?" value={thirdParties} onChange={setThirdParties} /><TripIncidentEvidencePicker files={files} onChange={setFiles} required={false} /><button type="button" disabled={!canSave || saving} onClick={() => void save()} className="w-full rounded-lg bg-amber-400 py-3 text-sm font-semibold disabled:opacity-50">{saving ? "Enviando..." : "Enviar formulario →"}</button></section></>}</main><Footer /></div>;
}
