import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router";
import SupervisorSidebar from "../components/supervisor/SupervisorSidebar";
import vehicleIcon from "../icons/supervisor/vehicle.svg";
import { supervisorVehiclesService } from "../services/supervisor-vehicles.service";
import type { SupervisorVehicle, SupervisorVehicleInput, VehicleType } from "../services/supervisor-vehicles.service";

const empty: SupervisorVehicleInput = { type: "camioneta", plate: "", transitLicense: null, brand: null, owner: null, currentMileage: 0, oilControlEnabled: true, oilIntervalKm: 5000, oilWarningMarginKm: 500, oilReferenceMileage: null, fumigationRequired: false, fumigationFrequencyDays: null, lastFumigationDate: null };
const name = () => { try { return JSON.parse(localStorage.getItem("user") ?? "null")?.nombre ?? "Supervisor"; } catch { return "Supervisor"; } };
const nullableNumber = (value: string): number | null => value === "" ? null : Number(value);

export default function SupervisorVehicleFormPage() {
    const navigate = useNavigate(); const { vehicleId } = useParams(); const id = Number(vehicleId); const editing = Number.isInteger(id) && id > 0;
    const [form, setForm] = useState<SupervisorVehicleInput>(empty); const [vehicle, setVehicle] = useState<SupervisorVehicle | null>(null);
    const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
    useEffect(() => { if (!editing) return; supervisorVehiclesService.findById(id).then((data) => { setVehicle(data); setForm(data); }).catch((reason) => setError(reason instanceof Error ? reason.message : "No fue posible consultar el vehículo")).finally(() => setLoading(false)); }, [editing, id]);
    const set = <K extends keyof SupervisorVehicleInput>(key: K, value: SupervisorVehicleInput[K]) => setForm((current) => ({ ...current, [key]: value }));
    const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(null); setSuccess(null); try { const result = editing ? await supervisorVehiclesService.update(id, form) : await supervisorVehiclesService.create(form); setVehicle(result); setForm(result); setSuccess(editing ? "Vehículo actualizado correctamente" : "Vehículo registrado correctamente"); if (!editing) navigate(`/supervisor/vehicles/${result.id}`, { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible guardar"); } finally { setSaving(false); } };
    const status = async () => { if (!vehicle) return; setSaving(true); setError(null); try { const result = await supervisorVehiclesService.updateStatus(vehicle.id, !vehicle.active); setVehicle(result); setForm(result); setSuccess(result.active ? "Vehículo activado" : "Vehículo desactivado"); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible cambiar el estado"); } finally { setSaving(false); } };
    if (loading) return <div className="p-10 text-center">Consultando vehículo...</div>;
    return <div className="min-h-dvh bg-gray-50"><SupervisorSidebar name={name()} active="vehiculos" /><main className="px-4 py-6 md:ml-64 md:px-8 lg:px-10">
        <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-amber-50"><img src={vehicleIcon} alt="" className="h-7 w-7" /></span><div><p className="text-xs uppercase tracking-wider text-amber-500">Gestión de flota</p><h1 className="text-2xl font-bold">{editing ? vehicle?.plate ?? "Vehículo" : "Registrar vehículo"}</h1><p className="text-sm text-gray-500">Datos generales y controles preventivos.</p></div></div><div className="flex gap-2"><button type="button" onClick={() => navigate("/supervisor/vehicles")} className="rounded-xl border bg-white px-5 py-3">Volver</button>{vehicle && <button type="button" onClick={status} disabled={saving} className={`rounded-xl px-5 py-3 font-semibold ${vehicle.active ? "border border-red-200 bg-red-50 text-red-600" : "bg-emerald-100 text-emerald-700"}`}>{vehicle.active ? "Desactivar" : "Activar"}</button>}</div></header>
        {error && <p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-red-600">{error}</p>}{success && <p className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-700">{success}</p>}
        <form onSubmit={submit} className="mt-6 space-y-6">
            <Card title="Información del vehículo"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Tipo de vehículo *"><select value={form.type} onChange={(e) => set("type", e.target.value as VehicleType)} className="control"><option value="camioneta">Camioneta</option><option value="motocicleta">Motocicleta</option><option value="motocarguero">Motocarguero</option><option value="carro">Carro</option></select></Field><Field label="Placa *"><input required value={form.plate} onChange={(e) => set("plate", e.target.value)} className="control uppercase" /></Field><Field label="Kilometraje actual *"><input required min={0} type="number" value={form.currentMileage} onChange={(e) => set("currentMileage", Number(e.target.value))} className="control" /></Field><Field label="Marca"><input value={form.brand ?? ""} onChange={(e) => set("brand", e.target.value || null)} className="control" /></Field><Field label="Licencia de tránsito"><input value={form.transitLicense ?? ""} onChange={(e) => set("transitLicense", e.target.value || null)} className="control" /></Field><Field label="Propietario"><input value={form.owner ?? ""} onChange={(e) => set("owner", e.target.value || null)} className="control" /></Field></div><p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-700">El kilometraje pertenece al vehículo, no al conductor. Nunca puede disminuir y cada aumento queda registrado.</p></Card>
            <Card title="Control de cambio de aceite" description="Genera alertas usando el kilometraje acumulado del vehículo." toggle={<Toggle checked={form.oilControlEnabled} onChange={(value) => set("oilControlEnabled", value)} />}>{form.oilControlEnabled && <div className="grid gap-4 md:grid-cols-3"><Field label="Intervalo de cambio (km) *"><input required min={500} type="number" value={form.oilIntervalKm ?? ""} onChange={(e) => set("oilIntervalKm", nullableNumber(e.target.value))} className="control" /></Field><Field label="Avisar cuando falten (km) *"><input required min={0} type="number" value={form.oilWarningMarginKm ?? ""} onChange={(e) => set("oilWarningMarginKm", nullableNumber(e.target.value))} className="control" /></Field><Field label="Kilometraje del último cambio"><input min={0} max={form.currentMileage} type="number" value={form.oilReferenceMileage ?? ""} onChange={(e) => set("oilReferenceMileage", nullableNumber(e.target.value))} placeholder="Vacío si no se conoce" className="control" /></Field></div>}{vehicle?.oilControlEnabled && <Alert status={vehicle.oilStatus} text={vehicle.nextOilChangeKm === null ? "Falta registrar un cambio de aceite de referencia." : `Próximo cambio: ${vehicle.nextOilChangeKm.toLocaleString("es-CO")} km · ${vehicle.oilRemainingKm?.toLocaleString("es-CO")} km restantes.`} />}</Card>
            <Card title="Control de fumigación" description="La alerta se calcula por fecha y frecuencia." toggle={<Toggle checked={form.fumigationRequired} onChange={(value) => set("fumigationRequired", value)} />}>{form.fumigationRequired && <div className="grid gap-4 md:grid-cols-2"><Field label="Frecuencia (días) *"><input required min={1} type="number" value={form.fumigationFrequencyDays ?? ""} onChange={(e) => set("fumigationFrequencyDays", nullableNumber(e.target.value))} className="control" /></Field><Field label="Última fumigación"><input type="date" value={form.lastFumigationDate ?? ""} onChange={(e) => set("lastFumigationDate", e.target.value || null)} className="control" /></Field></div>}{vehicle?.fumigationRequired && <Alert status={vehicle.fumigationStatus} text={vehicle.nextFumigationDate ? `Próxima fumigación: ${vehicle.nextFumigationDate}` : "Falta registrar una fumigación de referencia."} />}</Card>
            <footer className="sticky bottom-0 flex justify-end border-t bg-white/95 p-4 shadow-lg"><button disabled={saving} className="min-w-56 rounded-xl bg-amber-400 px-6 py-3 font-bold hover:bg-amber-500 disabled:opacity-50">{saving ? "Guardando..." : editing ? "Guardar cambios" : "Registrar vehículo"}</button></footer>
        </form></main></div>;
}

function Card({ title, description, toggle, children }: { title: string; description?: string; toggle?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-lg font-bold">{title}</h2>{description && <p className="text-sm text-gray-500">{description}</p>}</div>{toggle}</div>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-medium text-gray-700"><span>{label}</span>{children}</label>; }
function Toggle({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className={`relative h-7 w-12 rounded-full transition ${checked ? "bg-amber-400" : "bg-gray-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${checked ? "left-6" : "left-1"}`} /></button>; }
function Alert({ status, text }: { status: string; text: string }) { const danger = status === "overdue"; const warning = status === "upcoming" || status === "pending"; return <p className={`mt-5 rounded-xl border p-3 text-sm ${danger ? "border-red-200 bg-red-50 text-red-700" : warning ? "border-amber-200 bg-amber-50 text-amber-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{text}</p>; }
